package com.rve.rvkernelmanager.utils

import com.rve.rvkernelmanager.utils.Utils.exec

object BootServiceManager {
    private const val SCRIPT_PATH = "/usr/local/bin/rvkernel-boot.sh"
    private const val SERVICE_PATH = "/etc/systemd/system/rvkernel-boot.service"

    fun updateBootService(enableService: Boolean, turboEnabled: Boolean): Boolean {
        val scriptContent = buildString {
            appendLine("#!/bin/bash")
            appendLine("# Generated by RvKernel Manager")
            appendLine("if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then")
            appendLine("  echo ${if (turboEnabled) 0 else 1} > /sys/devices/system/cpu/intel_pstate/no_turbo")
            appendLine("elif [ -f /sys/devices/system/cpu/cpufreq/boost ]; then")
            appendLine("  echo ${if (turboEnabled) 1 else 0} > /sys/devices/system/cpu/cpufreq/boost")
            appendLine("fi")
        }

        val serviceContent = """
            [Unit]
            Description=RvKernel Manager Boot Settings
            After=multi-user.target

            [Service]
            Type=oneshot
            ExecStart=/bin/bash $SCRIPT_PATH

            [Install]
            WantedBy=multi-user.target
        """.trimIndent()

        val command = if (enableService) {
            "pkexec sh -c \"echo '$scriptContent' > $SCRIPT_PATH && " +
                    "chmod +x $SCRIPT_PATH && " +
                    "echo '$serviceContent' > $SERVICE_PATH && " +
                    "systemctl daemon-reload && " +
                    "systemctl enable rvkernel-boot.service && " +
                    "systemctl restart rvkernel-boot.service\""
        } else {
            "pkexec sh -c \"systemctl stop rvkernel-boot.service && " +
                    "systemctl disable rvkernel-boot.service && " +
                    "rm -f $SCRIPT_PATH $SERVICE_PATH && " +
                    "systemctl daemon-reload\""
        }

        return try {
            exec(command)
            true
        } catch (e: Exception) {
            e.printStackTrace()
            Log.e("BootManager", "Failed to update boot service", e)
            false
        }
    }
}